# kubectl create ns dev
# kubectl run n1 --image=nginx --port=80
# kubectl expose pod n1 --port=81 --target-port=80 –nodePort=31709 --name=svc1 --type=NodePort
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Deployment
metadata:
  name: n1
  labels:
    app: nginx
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: n1
      labels:
        app: nginx
      namespace: dev
    spec:
      containers:
      - name: nginx
        image: "nginx:2.0.0"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: n1
  labels:
    app: nginx
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: n1
      labels:
        app: nginx
      namespace: dev
    spec:
      containers:
      - name: nginx
        image: "nginx:2.0.0"
        ports:
        - containerPort: 80
---
  apiVersion: v1
kind: ReplicationController
metadata:
  name: n1
  labels:
    app: nginx
  namespace: dev
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: n1
      labels:
        app: nginx
      namespace: dev
    spec:
      containers:
      - name: nginx
        image: "nginx:latest"
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    app: nginx
  namespace: dev
spec:
  containers:
  - name: nginx
    image: "nginx:latest"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80
    nodePort: 31709

  
